/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package inspecoes;

import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.Vector;
import javax.swing.ImageIcon;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author 5701600
 */
public class Relatorio3 extends javax.swing.JFrame {

    Menu refer;
    DefaultTableModel REL3;

    /**
     * Creates new form Relatorio3
     */
    public Relatorio3(Menu refer, String mesi, String anoi, String mesf, String anof) throws SQLException {
        initComponents();
        REL3 = new DefaultTableModel();
        this.refer = refer;
        setLocationRelativeTo(null);
        setResizable(false);
        setLocationRelativeTo(null);
        setTitle("Relatório da Saude das Caixas entre " + mesi + "/" + anoi + " e " + mesf + "/" + anof);
        setVisible(true);
        relatorio3(mesi, anoi, mesf, anof);
        this.setIconImage(new ImageIcon(getClass().getResource("icol.png")).getImage());
        //bruna emanuele napoli simioni
    }

    public void relatorio3(String mesi, String anoi, String mesf, String anof) throws SQLException {
        REL3.addColumn("Ponto de Distribuição");
        REL3.addColumn("Problemas");
        REL3.addColumn("Problemas Possiveis");
        TabRel3.setModel(REL3);
        ResultSet r;
        r = refer.dbi.Rel3GetNomesCaixas();

        int[] rset = new int[2];

        String inicial = anoi + "-" + mesi + "-01";
        String final_ = anof + "-" + mesf + "-01";
        int qtdmeses = qtdmeses(mesi, anoi, mesf, anof);

        Vector row;

        ArrayList<Integer> set = new ArrayList();
        while (r.next()) {
            set.add(Integer.parseInt(r.getString("etiqueta")));
        }

        for (int a = 0; a < set.size(); a++) {

            row = new Vector();
            rset = refer.dbi.Rel3_Get(set.get(a).toString(), inicial, final_);
            row.add(set.get(a));
            row.add(rset[0]);
            row.add(rset[1] * qtdmeses);
            REL3.addRow(row);
        }

        TabRel3.removeAll();
        TabRel3.setModel(REL3);
    }

    public int qtdmeses(String mesi, String anoi, String mesf, String anof) {
        int qtdmeses = 0;
        int mesinicial = Integer.parseInt(mesi);
        int anoinicial = Integer.parseInt(anoi);
        int mesfinal = Integer.parseInt(mesf);
        int anofinal = Integer.parseInt(anof);

        for (int anoatual = anoinicial; anoatual <= anofinal; anoatual++) {
            if (anoinicial == anofinal) {

                for (int mesatual = mesinicial; mesatual <= mesfinal; mesatual++) {
                    qtdmeses++;
                }

            } else if (anoinicial == anoatual) {

                for (int mesatual = mesinicial; mesatual <= 12; mesatual++) {
                    qtdmeses++;
                }

            } else if (anofinal == anoatual) {

                for (int mesatual = 01; mesatual <= mesfinal; mesatual++) {
                    qtdmeses++;
                }

            } else {

                for (int mesatual = 01; mesatual <= 12; mesatual++) {
                    qtdmeses++;
                }
            }
        }

        return qtdmeses;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        TabRel3 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        TabRel3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(TabRel3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 575, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(24, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 356, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Relatorio3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Relatorio3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Relatorio3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Relatorio3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new Relatorio3().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable TabRel3;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
